#!/usr/bin/env node
/**
 * EngineeringPaper .epxyz generator (reverse-engineered from repository code paths).
 *
 * Usage:
 *   node agent/generate-epxyz.js
 *   node agent/generate-epxyz.js ./out/custom.epxyz "My Sheet"
 */

import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';

const outputPath = process.argv[2] || path.join('agent', 'generated-example.epxyz');
const title = process.argv[3] || 'Generated EngineeringPaper Sheet';

function nowIso() {
  return new Date().toISOString();
}

function buildSheetDocument({ title }) {
  const cells = [
    {
      type: 'documentation',
      id: 0,
      json: {
        ops: [
          { insert: 'Generated by Node.js script.\\n' }
        ]
      }
    },
    {
      type: 'math',
      id: 1,
      latex: 'x=2',
      config: null
    }
  ];

  return {
    data: {
      // Optional in loader, but included to match current writer behavior.
      version: 20260313,
      // Optional in loader, but included for compatibility and deterministic defaults.
      config: {
        mathCellConfig: {
          symbolicOutput: false,
          showIntermediateResults: false,
          formatOptions: {
            notation: 'auto',
            precision: 15,
            lowerExp: -3,
            upperExp: 5
          }
        },
        customBaseUnits: {
          mass: 'kg',
          length: 'm',
          time: 's',
          current: 'A',
          temperature: 'K',
          luminous_intensity: 'cd',
          amount_of_substance: 'mol',
          force: 'N',
          area: 'm^2',
          volume: 'm^3',
          energy: 'J',
          power: 'W',
          pressure: 'Pa',
          charge: 'C',
          capacitance: 'F',
          electric_potential: 'V',
          resistance: 'ohm',
          inductance: 'H',
          conductance: 'S',
          magnetic_flux: 'Wb',
          magnetic_flux_density: 'T',
          angle: 'rad',
          information: 'b'
        },
        simplifySymbolicExpressions: true,
        convertFloatsToFractions: true,
        fluidConfig: {
          fluid: 'Water',
          incompMixConc: 0.5,
          customMixture: [
            { fluid: 'R32', moleFraction: 0.697615 },
            { fluid: 'R125', moleFraction: 0.302385 }
          ]
        }
      },
      cells,
      title,
      // Keep empty so app recalculates fresh results if needed.
      results: [],
      system_results: [],
      codeCellResults: {},
      sub_results: [],
      nextId: 2,
      sheetId: crypto.randomUUID(),
      insertedSheets: []
    },
    history: [
      {
        url: title,
        hash: 'file',
        creation: nowIso()
      }
    ]
  };
}

const payload = buildSheetDocument({ title });
fs.mkdirSync(path.dirname(outputPath), { recursive: true });
fs.writeFileSync(outputPath, JSON.stringify(payload));
console.log(`Wrote ${outputPath}`);
